config/routes.rb
Sosms::Application.routes.draw do
  devise_for :users

  root :to => "home#index"

  post 'incoming/text'
  post 'incoming/call'

  resources :contacts
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  # Using has_many instead of has_one because people
  # might share a contact.
  #
  # Scenario: We have three friends Bill, Bob, and Rob.
  # Bill and Bob could both signup for SOSMS and use
  # Rob as a contact. Rob would then have more than one
  # user associated with his Contact "account"
  has_many :users

  attr_accessible :first_name, :last_name, :email, :phone_number, :voice, :sms, :user_id

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def text(message)
    Twilio.connect(config['TWILIO_SID'], config['TWILIO_TKN'])
    Twilio::Sms.message('4172082640', self.phone_number, message)
  end

  #def call
    #Twilio::Call.make('4172082640', self.phone_number, 'http://582dc2b5.dotcloud.com/incoming/call')
  #end

  def notify
   # if voice?
      #call
    if sms?
      text("#{overlord} has checked in with SOSMS. Despite disaster they're safe.")
    end
  end

  def overlord
    User.find(self.user_id).email
  end

  def to_param
    "#{id}-#{first_name}-#{last_name}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :phone_number

  has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  before_filter :authenticate_user!

  def index
    @user = current_user
    @contacts = @user.contacts
  end

  def new
    @contact = Contact.new

    respond_to do |format|
      format.html #new.haml
    end
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.user_id = current_user.id

    respond_to do |format|
      if @contact.save!
        format.html { redirect_to(@contact, flash[:notice] => "Contact saved!") }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def show
    @contact = Contact.find(params[:id])

    respond_to do |format|
      format.html #show.haml
    end
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])

    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        format.html { redirect_to(contacts_path, :notice => 'Contact updated!') }
      else
        format.html { render :action => 'edit' }
      end
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to(contacts_path) }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController
  BASE_URL = 'http://582dc2b5.dotcloud.com/'

  def text
    @user = User.find_by_phone_number(params[:From][1..-1])
    @user.contacts.each {|contact| contact.notify}

    render :xml => {:Sms => "Message received, contacts notified. Be safe!"}.to_xml(:root => 'Response')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/incoming_helper.rb
module IncomingHelper
end

app/helpers/text_helper.rb
module TextHelper
end

app/views/contacts/_form.haml
- semantic_form_for @contact do |form|
  - form.inputs do
    = form.input :first_name
    = form.input :last_name
    = form.input :email
    = form.input :phone_number
    = form.input :sms
  - form.buttons do
    = button_submit_tag "Create Contact"

app/views/contacts/edit.haml
%h1 Edit contact details
= render :partial => "form"

app/views/contacts/index.haml
%h1 Your contacts
= "No Contacts Yet!" if @contacts.blank?
.contact
- @contacts.each do |contact|
  #contact_name
    %b Name:
    = contact.full_name
  %br
  #contact_email
    %b Email:
    = contact.email
  %br
  #contact_phone
    %b Phone:
    = contact.phone_number
  %br
  #contact_methods
    %b Contact Methods:
    - if contact.voice
      Voice
    - if contact.sms
      SMS
  %br
    - button_group do
      = edit_button_link_to "edit", edit_contact_path(contact)
      = trash_button_link_to "delete", contact, :confirm => 'You sure?', :method => :delete
  %hr

app/views/contacts/new.haml
%h1 Add a contact
= render :partial => 'form'

app/views/contacts/show.haml
%h2#contact_show_header Contact Details
.contact_name
  #label Name:
  #value
    = @contact.full_name
%br
.contact_email
  #label Email Address:
  #value
    = @contact.email
%br
.contact_phone
  #label Phone Number:
  #value
    = @contact.phone_number
%br
- button_group do
  = primary_edit_button_link_to "Edit Contact Info", edit_contact_path
  = user_button_link_to "Add Another Contact", new_contact_path

app/views/home/index.haml
#markdown
  :markdown
    Welcome to SOSMS!
    -----------------
    SOSMS seeks to help connect survivors of disaster with their family and friends.

    How does it work?
    -----------------
    * Sign up for an account
    * Add contacts (people to be notified)
    * Text "SAFE" to **(417) 208-2640** to notify your contacts
%br
%a{:href => new_user_registration_path}
  %button.signUp Sign Up!

app/views/layouts/application.haml
!!!
%head
  %title SOSMS - We hope you never use it.
  = css3buttons_stylesheets :include_reset => false
  = stylesheet_link_tag :all, :formtastic
  = javascript_include_tag :defaults
  = csrf_meta_tag
  = image_tag "logo.png", :height => "50px"
  = render :partial => "shared/nav"
%body
  .notice
    = notice
  .alert
    = alert

  = yield

#footer
  = render :partial => "shared/footer"

app/views/shared/_footer.haml
%br
.footerContact
  %span#footerText
    Contact
  %span#footerText
    SOSMS
  %br
  %a{:href => "http://twitter.com/dfnkt"}
    = image_tag("twitter.png", :height => "25px")
  %a{:href => "mailto:caley.w@gmail.com"}
    = image_tag("gmail.png", :height => "20px")
  %span#footerNumber
    (417)208-2640

app/views/shared/_nav.haml
.nav
  - button_group do
    -#- if current_user
      = current_user.email
    - unless current_user
      = pill_button_link_to "Home", root_path
    - if current_user
      = pill_button_link_to "Home", contacts_path
      = user_pill_button_link_to "Add Contact", new_contact_path
      = negative_pill_button_link_to "Logout", destroy_user_session_path
    - else
      = primary_pill_button_link_to "Login", new_user_session_path